services:
  db:
    image: mysql:8.0
    container_name: django_crm_db
    restart: always
    environment:
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Using 3307 to avoid conflicts with local MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  web:
    build: .
    container_name: django_crm_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=crm
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

volumes:
  mysql_data:
  static_volume:
